### ISSUE TITLE
注入data方法后前，需要销毁data里的原始数据，却提示dropdown.destroy not undefined;

### ISSUE THREAD

**Issue by cliek** [Janking/dropdown#1]
这个插件初始化的时候，使用的json格式的数据，但是我ajax请求后改变json数据option里的东西不变，使用data注入时会出现两个下拉框，所以需要销毁前面的data数据，但是销毁函数提示报错，版本是1.1

**Comment by Janking** [comment]
@cliek 给你带来不便，非常抱歉，我马上修复。

**Comment by Janking** [comment]
@cliek 已新增`update`方法，版本为 1.1.3，最新代码请在GitHub上下载，具体使用请看 https://github.com/Janking/dropdown#updatearrayiscover
