### ISSUE TITLE
关于搜索大小写检索问题

### ISSUE THREAD

**Issue by FOXaaFOX** [Janking/dropdown#11]
不支持大写检索
js文件240行，条件少了个转大写
      $.each(data, function (key, value) {
        if (value.name.toUpperCase().indexOf(intputValue) > -1||value.name.toLowerCase().indexOf(intputValue) > -1|| '' + value.id === '' + intputValue) {
          result.push(value);
        }
      });

**Comment by Janking** [comment]
@FOXaaFOX  Thanks ! 已更新
