### ISSUE TITLE
2个优化建议

### ISSUE THREAD

**Issue by yangsen-cn** [Janking/dropdown#12]
<select >标签中默认没有option时，会报错，建议在第458行加上判断if(_this.name == null){_this.name = [];}

启动方法为什么不是$('#select_id').dropdown(.......)，由插件在select上层添加一个div

**Comment by Janking** [comment]
@yangsen-cn 谢谢你的建议！
第一个已经处理
第二个问题：如果JS往select上层添加一个div，那这个div就没办法额外加别的class，个人不建议这样做
