### ISSUE TITLE
如何在表单中点击清除按钮，让下拉框回到初始状态。

### ISSUE THREAD

**Issue by DaZhaoLis** [Janking/dropdown#15]
如何在表单中点击清除按钮，让下拉框回到初始状态。

**Comment by Janking** [comment]
@DaZhaoLis 谢谢你的支持和关注，目前缺少清除全部的按钮，建议你暂时在表单点击清除按钮时，调用一下 `$('.dropdown-clear-all').trigger('focusin')`

**Comment by Janking** [comment]
@DaZhaoLis version 1.2.0新增reset()方法

**Comment by DaZhaoLis** [comment]
@Janking 感谢您的new feature，不知道是否因为新版本导致模糊搜索功能失效，还是我的编写方法有误。
目前引入新版本后reset()测试通过，但是模糊搜索失效。
我回退了版本，通过.choose('',true)替代了reset()

**Comment by Janking** [comment]
@DaZhaoLis 模糊搜索功能失效问题应该是我新增分组名搜索时出bug了，现已修复
