### ISSUE TITLE
如何做联动呢，我在联动的时候遇到问题，第二个下拉框的时候 无法选中值，还有就是如何销毁初始化的下拉框，options?应该用什么代替。

### ISSUE THREAD

**Issue by luzongzhu** [Janking/dropdown#16]

**Comment by Janking** [comment]
@luzongzhu  https://github.com/Janking/dropdown#methods 你看一下这些方法能否帮到你

**Comment by luzongzhu** [comment]
您好 貌似没用用 我现在在二级筛选 初始化的时候  无法把下拉框初始化

**Comment by Janking** [comment]
@luzongzhu 你好，现在更新版本到`1.2.0`了，新增`reset()`方法
