### ISSUE TITLE
大哥，不好意思，再请教一个问题，如何在模糊搜索的时候不去搜索data-id

### ISSUE THREAD

**Issue by DaZhaoLis** [Janking/dropdown#17]
大哥，不好意思，再请教一个问题，如何在模糊搜索的时候不去搜索data-id

**Comment by DaZhaoLis** [comment]
@Janking 大哥救命

**Comment by Janking** [comment]
为什么不搜索id？

**Comment by Janking** [comment]
@DaZhaoLis 如果你要不搜索data-id，你可以自己修改一下源文件这一行
https://github.com/Janking/dropdown/blob/master/jquery.dropdown.js#L240

因为你这个需求实在太个性化了，我暂时不采纳，谢谢你的支持

**Comment by DaZhaoLis** [comment]
@Janking 我有一个车辆下拉列表，id是车辆的ITid，展示的名称是粤Bxxx。
例如，我搜索12 理论是只能搜索出12的车牌号。现在把id为12都搜索出来了。

**Comment by Janking** [comment]
@DaZhaoLis 暂时你先通过修改源代码处理吧，就在这https://github.com/Janking/dropdown/blob/master/jquery.dropdown.js#L240 
应该看得懂吧
