### ISSUE TITLE
Is there anyway to use onchange() call back function in label mode?

### ISSUE THREAD

**Issue by ridum** [Janking/dropdown#19]
Currently there is only this "choice" option that allow a user to in a callback function. This work well if the 'label' mode is not set. When the 'label'mode is set, the 'choice' function is not being called while the user clicking the erase button from the label to deselect a button. I have also tried chain binding to the original select but it does not work too.

**Comment by ridum** [comment]
I added 
 "  var _config = _dropdown.config;
      _config.choice.call(_dropdown, event);"
at the end of the delete function (before return) in this library so its guarantee to call the "choice" callback function after a deselect action be performed despite the label mode or not. "

**Comment by Janking** [comment]
@ridum Thanks , I will push the modify in next version
