### ISSUE TITLE
发现了两个BUG，不知道是否个例

### ISSUE THREAD

**Issue by roger2002** [Janking/dropdown#2]
1.当option的value是中文的时候,dropdown无法正常的拉取键值,data-value的值全部为空
2.choice回调函数无效
望解疑

**Comment by Janking** [comment]
@roger2002  谢谢你的使用，第一个问题是因为我的正则捕获value并不支持中文导致，我立马修复，第二个问题，能贴一下你的代码到jsfiddle或者codepen么？

**Comment by roger2002** [comment]
程序有BUG，回调函数只在多选情况下触发，单选不会，可以修改源文件搜索singleChoose，在该函数的末尾加上  非压缩版本 : _config.choice.call(_dropdown, event);  压缩版本 : t.choice.call(n,o) 即可

**Comment by Janking** [comment]
@roger2002 谢谢你反馈的问题，修复并更新，最新版本 version  1.1.4
