### ISSUE TITLE
when using European letters input where selected values are shown is hiding this selected values

### ISSUE THREAD

**Issue by ahromyak** [Janking/dropdown#20]
If useing russian letter input where selected values is displayed is empty. can you tell me how to resolve it?

**Comment by Janking** [comment]
@ahromyak hi~ can you give me an online example

**Comment by Janking** [comment]
@ahromyak 

Maybe the problem should be here . 

https://github.com/Janking/dropdown/blob/master/jquery.dropdown.js#L117

`/value="?([\w\u4E00-\u9FA5\uF900-\uFA2D]+)"?/`

This regular expression does not match Russian

should I use `/value="?(.+)"?/`  ?

**Comment by ahromyak** [comment]
hi it should probably allow any of chars in your select. can you add me to
skype? grigmen1

2017-10-31 3:07 GMT+02:00 Janking <notifications@github.com>:

**Comment by Janking** [comment]
@ahromyak I do not have Skype, but weichat 😂

**Comment by Janking** [comment]
fixed
