### ISSUE TITLE
下拉框的点击获取到一个id,再点击怎么取消获取id

### ISSUE THREAD

**Issue by Fun005** [Janking/dropdown#22]
![image](https://user-images.githubusercontent.com/10656183/32647409-ed2685e0-c62b-11e7-8541-b66a5bde01af.png)
如图，点击后再点击在页面上来说是取消的，但是数组里却一直在增加，要怎么去掉没选中的id呢

**Comment by Janking** [comment]
你好，因为id值要求唯一
