### ISSUE TITLE
如何获取data-id 值？

### ISSUE THREAD

**Issue by dannykln** [Janking/dropdown#23]
console.log($(this.name[0]) 得到的是

< span class="dropdown-selected">ccc< i class="del" data- id="danny"></i>< /span>

< span class="dropdown-selected">5< i class="del" data -id="vivien"></i>< /span>

可是怎么获取danny和vivien呢？

**Comment by Janking** [comment]
这个数据和select标签是同步的，你直接获取select的value 值就行了，谢谢你的支持

**Comment by dannykln** [comment]
嗯，谢谢你！
