### ISSUE TITLE
低版本的谷歌浏览器中点击事件失效

### ISSUE THREAD

**Issue by google-tmac** [Janking/dropdown#25]
今天发现在谷歌浏览器37.0.2062.0版本下，下拉列表都能初始化，数据也能动态加载，但是点击时没有任何反应，就跟被disabled一样，有谁可以知道对应的触发事件对象是哪个？google_tmac@sina.com，我的邮箱地址，希望大家能够提供一些线索

**Comment by Janking** [comment]
@google-tmac 已修复。谢谢反馈
