### ISSUE TITLE
发现了一个关于destroy的BUG

### ISSUE THREAD

**Issue by roger2002** [Janking/dropdown#3]
destroy之前没有取消控件的事件监听，会导致重新建立控件的时候出现多次触发event的BUG导致选择失效，在destroy()删除DOM元素之前先this.unbindEvent(); 可修复此BUG

**Comment by Janking** [comment]
@roger2002 谢谢，遗漏unbindEvent

**Comment by Janking** [comment]
@roger2002 已更新，版本不变
