### ISSUE TITLE
user cannot select some total pieces 

### ISSUE THREAD

**Issue by emresaracoglu** [Janking/dropdown#40]
Hello

I want to block selected amounts, for example; The user cannot total select 3,6,7,9,11 pieces options.

Is this possible?
Thank you.

**Comment by emresaracoglu** [comment]
I don't think I can tell it right. For example, the user chose two options, no problem. But I want a warning to appear when a total of 3 (6,7,8,11) options are selected.

The goal is to prevent the user from choosing 3 options. How can I make it appear that such a warning?

**Comment by shirishparsekar** [comment]
I don't know if I really understood your problem.
My guess is that you want to restrict number of selected options to 2. If the user selects more than 2 options, you want to show a warning message.
If that is correct, then check this 

https://github.com/Janking/dropdown/blob/master/index.html#L177
You need to use `limitCount: 2`.

**Comment by emresaracoglu** [comment]
I give an example

![test](https://user-images.githubusercontent.com/297968/49173069-b50a8200-f353-11e8-8573-169d0905ce52.png)

I tried to explain with the infographic above. I hope this time :)
Is this possible?

**Comment by shirishparsekar** [comment]
Unfortunately no. Not possible as of now. But you can always modify the script as per your needs. The source code is clean enough to read and modify :)

**Comment by emresaracoglu** [comment]
I see, I'll try this
Thank you @shirishparsekar

**Comment by Janking** [comment]
> I see, I'll try this
> Thank you @shirishparsekar

Welcome to contribute your code~
