### ISSUE TITLE
Pre-select options

### ISSUE THREAD

**Issue by nnmalex** [Janking/dropdown#5]
Hello,

How do I pre-select options on load?

Can it be done via callback?

**Comment by Janking** [comment]
@nnmalex  Two ways to set pre-select option

1.  `  <select> <option value="one" selected>  HelloKitty </option></select> `

2.  `[{id:"option value",value:"option text" , selected : true}]   `

the next version will add ` done ` callback .

**Comment by Janking** [comment]
@nnmalex version `1.1.5` had released
