### ISSUE TITLE
If the two selection boxes have hierarchical relationships, how to get them linked

### ISSUE THREAD

**Issue by isdux** [Janking/dropdown#6]
If you have this function, please tell me. If not, I will add myself. thanks in advance.

**Comment by Janking** [comment]
Sorry, There is no such feature for the time being, if you add cascade function , please pull a  request, Thanks !

**Comment by huyinxuan** [comment]
I  want to set multiple custom properties ,Please tell me how to do it

**Comment by Janking** [comment]
Hi @huyinxuan : 
There is no such feature for the time being，The next version will add it

**Comment by huyinxuan** [comment]
ok ， start  for you ， and  you can add some api ,  For example  provide choise fucntion . now  i will get all data for dome . is very bad , then have time can push some code

**Comment by Janking** [comment]
@huyinxuan 你还是用中文吧，不懂你说什么😄

**Comment by huyinxuan** [comment]
@Janking  尴尬 还以为你是老外呢   大概就是说 想增加一个 按状态选择的function咯 可以根据某个value 直接 设置选择状态 不需要再去拿到整个数据 设置它的selected状态

**Comment by Janking** [comment]
@huyinxuan 你的意思是提供一个value值，可以触发选中麽？例如这样: choose('a') A ?

**Comment by huyinxuan** [comment]
@Janking  是的

**Comment by Janking** [comment]
@huyinxuan 好的，你的建议很棒，这个周末会更新

**Comment by Janking** [comment]
@huyinxuan 你好，请问你需要扩展自定义属性的用途是什么？

**Comment by Janking** [comment]
@huyinxuan 已更新版本`1.1.6` 具体更新内容: https://github.com/Janking/dropdown

**Comment by huyinxuan** [comment]
@Janking  自定义属性的目的 就是在一个下拉在复杂场景中 一个value字段难以应付 后续判断场景  在配置中 传进去很多数据 但是你那边其实只会展示出 name 和 id =》 文本 和 data-value

**Comment by Janking** [comment]
@huyinxuan 你试试从choice函数的第二个参数中获取，如果还满足不了你的需求，我就去修改一下正则

**Comment by huyinxuan** [comment]
@Janking  啊  有两个参数？  我都不知道 你这边没注明啊 我都是把 e  和 this 自己传进去当参数来使的  两个参数是传递什么的？

**Comment by Janking** [comment]
@huyinxuan 你可以在回调函数中打印一下this和arguments，😁

**Comment by huyinxuan** [comment]
@Janking  嗯 目前我一些操作是这么做的 不过因为是 clone的 dom  所以this指向  和 我 设置自定义属性的节点 有不一样的 地方  492326552  你加下我qq 详聊

**Comment by Janking** [comment]
@huyinxuan 没用QQ，你可以加我微信 jankingzeng
