### ISSUE TITLE
多选、JSON渲染、分组功能，在 searchable = false 时，下拉数据不显示

### ISSUE THREAD

**Issue by wjl0814** [Janking/dropdown#8]
var jsonArray = [
            {
                "id": 1, // value值
                "disabled": false, // 是否禁选
                "groupName": "分组名",
                "groupId": 3,//分组ID
                "selected": false, // 是否选中
                "name": "Betty Deborah Jackson" // 名称
            },
            {
                "id": 2,
                "disabled": false,
                "groupName": "分组名",
                "groupId": 2,
                "selected": false,
                "name": "Jason Barbara Clark"
            }
        ]
        $('#dropdown-mul').dropdown({
            data: jsonArray,
            multipleMode: 'label',
            searchable: false,
            choice: function () {
                console.log(arguments, this);
            }
        });

**Comment by Janking** [comment]
@wjl0814 已修复，请下载最新版本 v1.1.7
